name: ci-test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  create-envfile:
    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: app.env
          fail_on_empty: true
          envkey_DB_DRIVER: ${{ secrets.DB_DRIVER }}
          envkey_DB_SOURCE: ${{ secrets.DB_SOURCE }}
          envkey_SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Install mockgen
        run: |
          go install go.uber.org/mock/mockgen@latest         

      - name: Run migrations
        run: make migrateup

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: make test
